# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robot_kontrol.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Robot_Kontrol(object):
    def setupUi(self, Robot_Kontrol):
        Robot_Kontrol.setObjectName("Robot_Kontrol")
        Robot_Kontrol.resize(487, 594)
        Robot_Kontrol.setMinimumSize(QtCore.QSize(487, 594))
        Robot_Kontrol.setMaximumSize(QtCore.QSize(487, 594))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setBold(False)
        font.setWeight(50)
        Robot_Kontrol.setFont(font)
        Robot_Kontrol.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Robot_Kontrol)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 180, 491, 181))
        self.widget.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.widget.setObjectName("widget")
        self.label_robot_kontrolleri = QtWidgets.QLabel(self.widget)
        self.label_robot_kontrolleri.setGeometry(QtCore.QRect(190, 10, 131, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_robot_kontrolleri.setFont(font)
        self.label_robot_kontrolleri.setObjectName("label_robot_kontrolleri")
        self.button_forward = QtWidgets.QPushButton(self.widget)
        self.button_forward.setGeometry(QtCore.QRect(210, 50, 89, 31))
        self.button_forward.setStyleSheet("color: rgb(238, 238, 236);\n"
"background-color: rgb(143, 89, 2);")
        self.button_forward.setObjectName("button_forward")
        self.button_right = QtWidgets.QPushButton(self.widget)
        self.button_right.setGeometry(QtCore.QRect(310, 90, 89, 31))
        self.button_right.setStyleSheet("color: rgb(238, 238, 236);\n"
"background-color: rgb(143, 89, 2);")
        self.button_right.setObjectName("button_right")
        self.button_stop = QtWidgets.QPushButton(self.widget)
        self.button_stop.setGeometry(QtCore.QRect(210, 90, 89, 31))
        self.button_stop.setStyleSheet("color: rgb(238, 238, 236);\n"
"background-color: rgb(143, 89, 2);\n"
"")
        self.button_stop.setObjectName("button_stop")
        self.button_back = QtWidgets.QPushButton(self.widget)
        self.button_back.setGeometry(QtCore.QRect(210, 130, 89, 31))
        self.button_back.setStyleSheet("color: rgb(238, 238, 236);\n"
"background-color: rgb(143, 89, 2);")
        self.button_back.setObjectName("button_back")
        self.button_left = QtWidgets.QPushButton(self.widget)
        self.button_left.setGeometry(QtCore.QRect(110, 90, 89, 31))
        self.button_left.setStyleSheet("color: rgb(238, 238, 236);\n"
"background-color: rgb(143, 89, 2);")
        self.button_left.setObjectName("button_left")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 491, 181))
        self.widget_2.setStyleSheet("background-color: rgb(115, 210, 22);")
        self.widget_2.setObjectName("widget_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.widget_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(60, 70, 361, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.line_ms = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_ms.setReadOnly(True)
        self.line_ms.setObjectName("line_ms")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_ms)
        self.label_rads = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_rads.setFont(font)
        self.label_rads.setObjectName("label_rads")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_rads)
        self.line_rads = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_rads.setReadOnly(True)
        self.line_rads.setObjectName("line_rads")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_rads)
        self.label_ms = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ms.setFont(font)
        self.label_ms.setObjectName("label_ms")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_ms)
        self.label_hiz_bilgileri = QtWidgets.QLabel(self.widget_2)
        self.label_hiz_bilgileri.setGeometry(QtCore.QRect(200, 20, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_hiz_bilgileri.setFont(font)
        self.label_hiz_bilgileri.setObjectName("label_hiz_bilgileri")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(0, 360, 491, 221))
        self.widget_3.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.widget_3.setObjectName("widget_3")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.widget_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(50, 60, 361, 71))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_x = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_x.setFont(font)
        self.label_x.setObjectName("label_x")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_x)
        self.line_x = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.line_x.setReadOnly(True)
        self.line_x.setObjectName("line_x")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_x)
        self.label_y = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_y.setFont(font)
        self.label_y.setObjectName("label_y")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_y)
        self.line_y = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.line_y.setReadOnly(True)
        self.line_y.setObjectName("line_y")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_y)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(190, 20, 131, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        Robot_Kontrol.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Robot_Kontrol)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 487, 22))
        self.menubar.setObjectName("menubar")
        Robot_Kontrol.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Robot_Kontrol)
        self.statusbar.setObjectName("statusbar")
        Robot_Kontrol.setStatusBar(self.statusbar)

        self.retranslateUi(Robot_Kontrol)
        QtCore.QMetaObject.connectSlotsByName(Robot_Kontrol)

    def retranslateUi(self, Robot_Kontrol):
        _translate = QtCore.QCoreApplication.translate
        Robot_Kontrol.setWindowTitle(_translate("Robot_Kontrol", "KOL-KAR S"))
        self.label_robot_kontrolleri.setText(_translate("Robot_Kontrol", "ROBOT KONTROL"))
        self.button_forward.setText(_translate("Robot_Kontrol", "İleri"))
        self.button_right.setText(_translate("Robot_Kontrol", "Sağ"))
        self.button_stop.setText(_translate("Robot_Kontrol", "Dur"))
        self.button_back.setText(_translate("Robot_Kontrol", "Geri"))
        self.button_left.setText(_translate("Robot_Kontrol", "Sol"))
        self.label_rads.setText(_translate("Robot_Kontrol", " Açısal Hız (rad/s):"))
        self.label_ms.setText(_translate("Robot_Kontrol", " Lineer Hız (m/s):"))
        self.label_hiz_bilgileri.setText(_translate("Robot_Kontrol", "HIZ BİLGİLERİ"))
        self.label_x.setText(_translate("Robot_Kontrol", "Konum x (m):"))
        self.label_y.setText(_translate("Robot_Kontrol", "Konum y (m):"))
        self.label_3.setText(_translate("Robot_Kontrol", "KONUM BİLGİLERİ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Robot_Kontrol = QtWidgets.QMainWindow()
    ui = Ui_Robot_Kontrol()
    ui.setupUi(Robot_Kontrol)
    Robot_Kontrol.show()
    sys.exit(app.exec_())

